### ISSUE TITLE
Wrong timestamp if internet is not available.

### ISSUE THREAD

**Issue by Nono118** [K1WIZ/ESP8266-8x32-Matrix-clock#1]
I setup a wireless hotspot but turn OFF the internet access. Power up the clock, clock starts up, gets connected but starts time at 8:00. It should have shown a get time error coz e.g power trip will cause the time to be wrong.

**Comment by K1WIZ** [comment]
Please feel free to submit a pull request and I will be happy to test it and merge it into the project.

**Comment by K1WIZ** [comment]
Closing issue as this is not a typical use case.  Please feel free to submit a pull request against the latest master code.
