### ISSUE TITLE
Date displayed sometimes is wrong.

### ISSUE THREAD

**Issue by Nono118** [K1WIZ/ESP8266-8x32-Matrix-clock#4]
`printStringWithShift(date.c_str(),40);  //Display date onto LED, shift delay 40`

This line which was originally //commented out// is meant to display the date every 30sec to the MAX7219.

There's a date bug in the way the code is written. The time & date are taken from a HTTP source which is at GMT=0. If you're outside of GMT=0, then your date will be wrong at certain times of the day, and gets corrected only when your timezone finally crosses GMT=0. This cannot be resolved, unless rewrite the code to use NTP style time fetching. 

Someone must have knew it and //commented out// the date display function.

**Comment by K1WIZ** [comment]
Please feel free to submit a pull request and I'll be happy to test it and merge it into the project  :)

**Comment by K1WIZ** [comment]
this functionality has been removed from the project.  If you'd like to reintroduce it, please feel free to submit a pull request against the current master.
