### ISSUE TITLE
Invalid operands of types double and long int to binary operator

### ISSUE THREAD

**Issue by Hamrun** [K1WIZ/ESP8266-8x32-Matrix-clock#5]
First of all thanks for the code.  When I am compiling this program, on line 329, (long epoch = round( curEpoch + 3600 * ( utcOffset + summerTime ) + 86400L ) % 86400L;) i am getting this invalid operands error. Maybe there is an update about this . 

Thanks

**Comment by damver** [comment]
already have a fix??

**Comment by Hamrun** [comment]
Hello damver ,

Try this 👍 

void updateTime()
{
  long curEpoch = localEpoc + ((millis() - localMillisAtUpdate) / 1000);
   long epoch = (long)round( curEpoch + 3600 * ( utcOffset + summerTime ) + 86400L ) % 86400L;
  epoch = epoch % 86400L;
  h = ((epoch  % 86400L) / 3600) % 24;
  m = (epoch % 3600) / 60;
  s = epoch % 60;

Hope that it will be of help .

**Comment by K1WIZ** [comment]
This fix has been implemented in a recent pull request that has been merged.  Closing issue.
