### ISSUE TITLE
the Matriz

### ISSUE THREAD

**Issue by anchite** [K1WIZ/ESP8266-8x32-Matrix-clock#6]
My time is appearing on the display in a vertical position, how to put it in a horizontal position?

**Comment by wl11lm** [comment]
Change: #define ROTATE 90
To: #define ROTATE 270

**Comment by damver** [comment]
didnt u get a error message?

like: invalid operands of types 'float' and 'long int' to binary 'operator%'

**Comment by K1WIZ** [comment]
unable to reproduce
