### ISSUE TITLE
Degree symbol "°" for showing temperature

### ISSUE THREAD

**Issue by suldobrasil70** [K1WIZ/ESP8266-8x32-Matrix-clock#7]
Thank you for this great code. I have it working for 2 years already and I have added a loop to show my pool's water temperature every 30 seconds. The Nodemcu picks up the value thru mqtt. However, I have not managed to show the degree Symbol (°) on the max7219.
I see you have it defined in the fonts.h file, but how do I show it on the display?
thanks in advance

**Comment by K1WIZ** [comment]
I'm unable to reproduce this without a copy of the code you are working with.
