### ISSUE TITLE
Clock Display is Not Working

### ISSUE THREAD

**Issue by j-vaughn** [K1WIZ/ESP8266-8x32-Matrix-clock#9]
I just downloaded this project and wrote it to a Wemos D1 MIni with an MAX7219 attached.  The output to the screen with the function `printStringWithShift` works perfectly but when the clock comes up, it displays 00:00 for a split second (added a delay in `loop()` to see this) and then goes to gibberish.  

Not sure if maybe there was a library update that broke something or if I'm just doing something wrong.

Thanks,
James

**Comment by K1WIZ** [comment]
I'm unable to reproduce.   please ensure you are using the header max7219.h file packaged with this project.   

Alternatively, you can also flash the newly released binary version using standard flashing tools:
https://github.com/K1WIZ/ESP8266-8x32-Matrix-clock/releases/tag/v1.0-stable
